### PR TITLE
Add list for examples in PG

### PR DESCRIPTION
**Pull request by TobiasNx**
Add an example for every flux command

Related to https://github.com/metafacture/metafacture-core/issues/488

### CODE REVIEW

**Comment by TobiasNx** [comment]
Do not merge this pr

**Comment by fsteeg** [comment]
> Do not merge this pr

Dafür sind doch drafts da, siehe oben rechts, bei "Reviewers":

> Still in progress? Convert to draft

**Comment by dr0i** [comment]
If we simply omit the 3. column when we don't have an example to PG we would simply leave the link, see https://github.com/metafacture/metafacture-core/pull/509 .

**Comment by dr0i** [comment]
I think this definitely improves our documentation :+1: (see example in https://github.com/metafacture/metafacture-core/pull/509).
If you are ok with leaving the 3. column empty we could merge this (possibly after https://github.com/metafacture/metafacture-core/pull/509 is merged). We can consecutively improve this table.

**Review by dr0i — APPROVED** [review]

**Comment by TobiasNx** [comment]
> > Do not merge this pr
> 
> Dafür sind doch drafts da, siehe oben rechts, bei "Reviewers":
> 
> > Still in progress? Convert to draft

But not via the Github app on my phone.

**Comment by dr0i** [comment]
I don't understand. I've implement to load a tsv. Now in https://github.com/metafacture/metafacture-playground/pull/148 the examples are organized in different flat files?

**Comment by TobiasNx** [comment]
I will update the file! We talked about it two weeks ago, if we would prefer literal links like `https://metafacture.org/playground/as-lines`. For this we need the links in the playground.

**Comment by dr0i** [comment]
ah - ok, good :)

**Comment by dr0i** [comment]
Deployed to https://github.com/metafacture/metafacture-documentation/blob/master/flux-commands.md.

**Pull request merged**
