### PR TITLE
Add how to update and publish flux-commands.md

### PR DESCRIPTION
**Pull request by dr0i**
In order of improving the documentation this should help to understand how to produce an improved flux-commands.md.

### CODE REVIEW

**Comment by dr0i** [comment]
Hm, maybe - let's ask for opinion from @fsteeg.
My first thought was "flux-command.md is stored in this repo, so let's document here how to build it properly".

**Comment by fsteeg** [comment]
I think here is the right place, since it's published here.

(Also this is a temporary state, see https://github.com/metafacture/metafacture-core/issues/368.)

**Comment by TobiasNx** [comment]
okay then go for it +1

**Comment by dr0i** [comment]
>Also this is a temporary state

 you mean "although". 
If metafacture/metafacture-core#368 is ready we could (should?) move this how-to to https://github.com/metafacture/metafacture.github.io/docs/main .

Merged for the time being and closed.

**Comment by fsteeg** [comment]
> you mean "although".

No, I meant it both in support of not moving it elsewhere (since it's temporary anyway), and as in "let me add that".

**Comment by dr0i** [comment]
I don't understand. Let's clarify. What do you mean exactly by  "this is a temporary state"? I thought you meant this repo (metafacture-documentation), while the future ordinary place would be in metafacture.github.io/docs/main . Or should the flux-commands.md be hold in _two_ (three?) places - here _and_ in metafacture.github.io/docs/main[releases...] ?

**Comment by fsteeg** [comment]
(Clarified in our meeting, we'll see where the file will be in the future, but for now it's good here)

**Pull request merged**
