### PR TITLE
Change callout for notes #28

### PR DESCRIPTION
**Pull request by TobiasNx**

### CODE REVIEW

**Review by Phu2 — APPROVED** [review]

**Comment by blackwinter** [comment]
Just out of curiosity: Where is this syntax documented? It's not supported by [GFM](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).

**Comment by TobiasNx** [comment]
> Just out of curiosity: Where is this syntax documented? It's not supported by [GFM](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).

https://just-the-docs.com/

**Comment by blackwinter** [comment]
Thanks. Too bad it doesn't support the GFM syntax.

But you need to configure the colors for [callouts](https://just-the-docs.com/docs/ui-components/callouts/), don't you? It doesn't have any effect yet.

**Comment by Phu2** [comment]
> But you need to [configure](https://just-the-docs.com/docs/configuration/#callouts) the colors for [callouts](https://just-the-docs.com/docs/ui-components/callouts/), don't you? It doesn't have any effect yet.

It is now configured https://github.com/metafacture/metafacture-documentation/commit/6c1659c26d68df1c06e9e22e38487b7a6d99478d

**Pull request merged**
